### ISSUE TITLE
Make sure that only supported number of nodes can be created

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#103]
Due to the port mapping (reservation of ports), some of the services can only be started a max number of times, otherwise there will be port conflicts. 

* zookeeper: 3
* kafka-broker: 6
* schema-registry: 2
* kafka-rest: 3
* kafka-connect: 3
* ksqldb-server: 3
* datanode: 6
* streamsets: 3
* streamsets-transformer: 3
* cassandra: 3
* dse: 3
* mosquitto: 3

**Comment by ufasoli** [comment]
Missing variables for :

- Kafka-rest 
- streamsets
- streamsets-transformer
- cassandra
