### ISSUE TITLE
When generating a stack with the subfolder option, the folder is owned by root user

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#114]
After a

```
platys gen --structure subfolder
```

the folder with the generated artifacts is owned by `root` but it should be owned by the user running `platys gen`.

**Comment by ufasoli** [comment]
the base folder is generated using python at has the right permissions the issue is in the .sh file with the command :

` cp -r /opt/mdps-gen/static-data/* /opt/mdps-gen/destination `

Since the container starts as root

**Comment by gschmutz** [comment]
That's correct, the base folder is created with the right permissions and the "platys user" being the owner. 

It's all the files inside the folder, which are owned by root, not just the static data but also docker-compose.yml. In the old bash script I resolved the issue by running the container with the current user using this option `--user $(id -u):$(id -g)`

```
docker run --rm -v "${PWD}":/opt/mdps-gen/conf -v "${destination}":/opt/mdps-gen/destination -e CONFIG_URL="${CONFIG_URL}" -e VERBOSE="${VERBOSE}" -e DEL_EMPTY_LINES=1 --user $(id -u):$(id -g) "${stack_name:-trivadis/platys-modern-data-platform}":"${stack_version:-1.2.0}
```

Could you do that from the Docker SDK for Python as well?

**Comment by ufasoli** [comment]
This was my initial thought too but at the moment from the python SDK I have permission issues (since folders are owned by root)
