### ISSUE TITLE
Platys on Windows is limited to Python3.7

### ISSUE THREAD

**Issue by AronAWeller** [TrivadisPF/platys#17]
Using Platys on Windows depends on exactly Python 3.7.x.
Working on a Windows with Python 3.8 brings the following Error : 

![Platys-Error](https://user-images.githubusercontent.com/26358453/82327343-8a483980-99de-11ea-981e-da3f29f76a19.jpg)

Message as Text : The code cannot proceed because python37.dll was not found.

Reproduce the Error : (Init Platys using cmd.exe. Powershell suppresses the error and just does not do anything.)
Command used in cmd-Terminal => platys init -n platys-demo-platform -sn trivadis/platys-modern-data-platform -sv 1.2.0

Proposal for fix : Check for Python >= 3.7

Please contact me if you got questions.

Regards, Aron

**Comment by ufasoli** [comment]
Hi Araron, 
Yes this is a big issue for us especially in Windows when doing the cross-compilation this is why we would like to move away from this and have platys provided as a docker container

**Comment by ufasoli** [comment]
This should normally be fixed after closing #20
