### ISSUE TITLE
Port mdps_generate bash script to Windows

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#25]
The `mdps_generate.sh` script currently works for Linux and Mac. 

We need support for Windows in the same way, so that it can be downloaded and run from Windows.

**Comment by gszecsenyi** [comment]
I executed it in GitBash (which is the part of git release for windows), and I get the following error from docker: 

`gsz@LTGSZ02 MINGW64 ~/modern-data-analytics-stack/dynamic-stack (master)
$ . ./mdps-generate.sh custom.yml "c:\\ABC\\" 1.0
Running the Modern Data Platform Stack Generator ....
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Mount denied:
The source path "C:/ABC"
doesn't exist and is not known to Docker.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
sed: can't read c:\ABC\/docker-compose.yml: No such file or directory
Modern Data Platform Stack generated successfully to c:\ABC\
`

**Comment by gschmutz** [comment]
@gszecsenyi  I was not able to make it work with relative and therefore used ${PWD} in the command. There are no hardcoded unix directories. The ones in bold (the first two) are inside the docker container. 

A relative filename for `custom.yml` doesn't work on linux either, due to the volume mapping into the docker container. Could you try to pass `c:\ABC\config\custom.yml`, assuming that you have it inside the ABC folder.

**Comment by ufasoli** [comment]
Hi, at this point and seeing the submitted issues for enhancements (remote server upload for example) i'm wondering if it wouldn't be better to write the script in Python and use a compiler as http://nuitka.net to translate it to the target systems (windows and linux) rather than maintaining 2 scripts

**Comment by lucafurrer** [comment]
I think it would be a great idea if something like this is possible. While testing I had written have of the script in powershell, hence a completed it and shared it with the world. A general version for all platforms would be preferable.

**Comment by gschmutz** [comment]
As long as the install is still as simple as a curl or wget and maybe changing the mode of the file to be an executable, it's fine for me. As Luca already mentioned, would prefer not having to install additional software. Would be interesting to know how docker-compose works.

**Comment by ufasoli** [comment]
No I agree, no extra dependecies is a must, ideally we could have the python script in the repository and 2 pre-compiled versions of the script for windows and linux, that being said it's true that if I'm not mistaken docker-compose runs using python and since docker-compose is required maybe there's not even a necessity to compile the script

**Comment by gschmutz** [comment]
Actually the portability between Windows and Linux can also be achieved by adding as much as possible to the docker container which is run by the script or even to another, additional container to be more modular. 

Both #29 and #45 might work that way.

**Comment by gschmutz** [comment]
We will move the logic of the bash script to a portable python-based implementation (#76). By that the powershell implementation will no longer be necessary.

**Comment by gschmutz** [comment]
a first implementation of the python script has been published this week.
