### ISSUE TITLE
Add more verbose output to `platys version`

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#25]
Change the output of the `platys version` command to 

```
$ platys version
Platys - Trivadis Platform in a Box - v2.3.0
https://github.com/trivadispf/platys
Copyright (c) 2018-2020, Trivadis AG
```

would it be possible to replace/set the version number automatically from the build?

**Comment by ufasoli** [comment]
Modified so version is taken from a constant not from build for the moment (this should be an evolution)
