### ISSUE TITLE
Add a Python container to the stack

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#32]
Add the <https://hub.docker.com/_/python> container to the stack

**Comment by ufasoli** [comment]
Hi Guido,
I can take this one too, are there any specific requirements (container communication for example) or just adding the container and updating the docs

**Comment by gschmutz** [comment]
Hi Ulises, I'm no longer sure how much value such a container really has. Python is also available in Jupyter notebook. But of course this way we would have more control on the release of python to use and maybe an added value would be if optionally a script could be specified which is automatically executed upon starting the container.

**Comment by gschmutz** [comment]
Another use case where an additional python container is definitely useful is for support of ARM hardware, where both Zeppelin and Jupyter with the current images have no support for.

**Comment by ufasoli** [comment]
Agreed, will take a look into this when I get back from southern France Tuesday 😁
