### ISSUE TITLE
platys init creates the config.yml with no rw rights

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#35]
A `platys init --platform-name platys-demo-platform --stack-version 1.6.0 -f --structure flat` creates the config.yml with the right owner but without any rights on it:

```
docker@ubuntu:~/platys-test$ ls -lsa
total 20
 4 drwxr-xr-x  2 docker docker 4096 Aug  7 05:41 .
 4 drwxr-xr-x 57 docker docker 4096 Aug  7 05:14 ..
12 ----------  1 docker docker 8691 Aug  7 05:41 config.yml
```

**Comment by ufasoli** [comment]
Config file is now created with 755 permission
