### ISSUE TITLE
Create a script which allows for clearing the container-volume folder

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#58]
The `container-volume` folder holds all the data which containers map to the docker host. It is initialized (folder structure) when generating the stack for the first time or when new services are added.

This item should provide a script which clears the data inside the folder structure, without removing the original structure, as it is necessary so that the container do not create them with wrong privileges.

**Comment by ufasoli** [comment]
if I understand correctly the idea would be to create a separate script 'clean-volumes' which deletes the content of the folder whilst keeping the 'skeleton' folder's tree

**Comment by ufasoli** [comment]
finally this will be ported to the python cli

**Comment by gschmutz** [comment]
One idea for handling these folders is to add another label to each service in the docker-compose.yml, describing the needed folders on the docker host, similar to the work done for the URLs of Web UIs, and APIs (see #36). 

Currently the folders inside `container-volume` are created because they are check-in into the `static-data` folder, which is copied into the current folder when running the generator. This is necessary, otherwise these folders are created with the rights of the container (often root), with the downside that these folders are not accessible by the docker host.

**Comment by ufasoli** [comment]
added new command : 
> clean 

with required argument 

> --folder
